.\" Manpage for power_series.
.TH man 1 "28 Apr 2020" "1.0" "power_series man page"
.SH NAME
power_series \- example applicationworld 
.SH SYNOPSIS
power_series
.SH DESCRIPTION
power_series todo ...
.SH OPTIONS
power_series todo ...
.SH BUGS
No known bugs.
.SH AUTHOR
@@APPP_AUTHOR@@ @@AUTHOR_EMAIL@@